chrome_map_path = "obj-aarch64-apple-darwin24.6.0/chrome-map.json"
component_paths = [
    "toolkit/content/widgets/moz-*/**/*",
    "toolkit/themes/shared/design-system/storybook/*",
]
globals_stylesheets = [
    "toolkit/themes/shared/design-system/*.css",
    "toolkit/themes/shared/in-content/common-shared.css",
]
docs_paths = [
    "browser/components/storybook/docs/*.stories.md",
]
