//! Generates supporting files that don't come from Firefox source: `index.mjs` entry points,
//! the `<acorn-icon>` web component, and the Fluent localization setup module.

use std::path::Path;

use crate::dependency_graph::{DependencyGraph, FileType, TargetLocation};
use crate::errors::{Error, Result};

/// Generates `index.mjs` entry points for library consumption:
/// - Per-component `dist/components/{name}/index.mjs` -- re-exports the component
/// - Root `dist/index.mjs` -- imports all components (registers all custom elements)
pub fn generate_index_files(dep_graph: &DependencyGraph, output_dir: &Path) -> Result<()> {
    // Collect (component_name, filename) for all JsComponent files
    let mut components: Vec<(String, String)> = Vec::new();

    for file in dep_graph.all_files() {
        if file.file_type == FileType::JsComponent
            && let TargetLocation::Component(ref name) = file.target_location
            && let Some(filename) = file.path.file_name().and_then(|s| s.to_str())
        {
            components.push((name.clone(), filename.to_string()));
        }
    }

    components.sort();
    components.dedup();

    // Generate per-component index.mjs
    for (name, filename) in &components {
        let content = format!(
            "// Auto-generated by mozcomp. Do not edit.\n\
             export * from \"./{filename}\";\n\
             import \"./{filename}\";\n"
        );
        let path = output_dir.join("components").join(name).join("index.mjs");
        std::fs::write(&path, content).map_err(|e| {
            Error::Custom(format!("Failed to write component index for {name}: {e}"))
        })?;
    }

    // Generate root index.mjs
    let imports: String = components
        .iter()
        .map(|(name, filename)| format!("import \"./components/{name}/{filename}\";"))
        .collect::<Vec<_>>()
        .join("\n");

    let content = format!(
        "// Auto-generated by mozcomp. Do not edit.\n\
         // Imports all components, registering them as custom elements.\n\
         {imports}\n"
    );
    let path = output_dir.join("index.mjs");
    std::fs::write(&path, content).map_err(|e| {
        Error::Custom(format!("Failed to write root index.mjs: {e}"))
    })?;

    eprintln!("Generated index files for {} components", components.len());
    Ok(())
}

/// Generates the `<acorn-icon>` custom element at `{output_dir}/dependencies/acorn-icon.mjs`.
///
/// This lightweight component uses CSS `mask-image` to render SVG icons that inherit
/// color from the parent element's `color` CSS property, replacing Firefox's proprietary
/// `-moz-context-properties` mechanism.
pub fn generate_acorn_icon_component(output_dir: &Path) -> Result<()> {
    let component_content = r#"// Auto-generated by mozcomp. Do not edit.
// Provides a cross-browser colorable SVG icon element using CSS mask-image.

class AcornIcon extends HTMLElement {
  static observedAttributes = ["src", "width", "height"];

  constructor() {
    super();
    this.attachShadow({ mode: "open" });
    this.shadowRoot.innerHTML = `<style>
      :host {
        display: inline-block;
        width: var(--acorn-icon-size, 16px);
        height: var(--acorn-icon-size, 16px);
        background-color: currentColor;
        -webkit-mask: var(--acorn-icon-src) no-repeat center / contain;
        mask: var(--acorn-icon-src) no-repeat center / contain;
      }
    </style>`;
  }

  attributeChangedCallback(name, _oldVal, newVal) {
    if (name === "src") {
      this.style.setProperty("--acorn-icon-src", `url("${newVal}")`);
    } else if (name === "width" || name === "height") {
      const size = newVal?.endsWith("px") ? newVal : newVal + "px";
      this.style.setProperty("--acorn-icon-size", size);
    }
  }

  connectedCallback() {
    const src = this.getAttribute("src");
    if (src) {
      this.style.setProperty("--acorn-icon-src", `url("${src}")`);
    }
    const w = this.getAttribute("width") || this.getAttribute("height");
    if (w) {
      const size = w.endsWith("px") ? w : w + "px";
      this.style.setProperty("--acorn-icon-size", size);
    }
  }
}

if (!customElements.get("acorn-icon")) {
  customElements.define("acorn-icon", AcornIcon);
}
"#;

    let deps_dir = output_dir.join("dependencies");
    std::fs::create_dir_all(&deps_dir).map_err(|e| {
        Error::Custom(format!(
            "Failed to create dependencies directory: {:?}: {e}",
            deps_dir
        ))
    })?;

    let output_path = deps_dir.join("acorn-icon.mjs");
    std::fs::write(&output_path, component_content).map_err(|e| {
        Error::Custom(format!("Failed to write acorn-icon.mjs: {e}"))
    })?;

    Ok(())
}

/// Generates the optional `{output_dir}/fluent-setup.mjs` — a self-contained helper
/// for consumers who want Fluent localization. Components render English by default
/// without this; importing it enables `document.l10n` for automatic translation of
/// all `data-l10n-id` attributes.
pub fn generate_fluent_setup(output_dir: &Path, ftl_files: &[String]) -> Result<()> {
    let mut sorted_files = ftl_files.to_vec();
    sorted_files.sort();

    let ftl_list = sorted_files
        .iter()
        .map(|f| format!("  \"{f}\""))
        .collect::<Vec<_>>()
        .join(",\n");

    let module_content = format!(
        r#"// Auto-generated by mozcomp. Do not edit.
// Optional Fluent localization setup. Components render English by default.
// Import and call initFluent() to enable localized strings via document.l10n.

export const FTL_FILES = [
{ftl_list}
];

function _defaultFetchFTL(ftlPath, locale) {{
  const url = new URL(`./locales/${{locale}}/${{ftlPath}}`, import.meta.url);
  return fetch(url).then(r => {{
    if (!r.ok) throw new Error(`${{r.status}}`);
    return r.text();
  }});
}}

/**
 * Sets up Mozilla Fluent localization for acorn-web components.
 * All elements with data-l10n-id will be translated automatically.
 *
 * @param {{Object}} [options]
 * @param {{string}} [options.locale='en-US'] - BCP 47 locale tag
 * @param {{Function}} [options.fetchFTL] - async (ftlPath, locale) => string
 */
export async function initFluent(options = {{}}) {{
  const locale = options.locale ?? "en-US";
  const fetchFTL = options.fetchFTL ?? _defaultFetchFTL;

  try {{
    const {{ FluentBundle, FluentResource }} = await import("@fluent/bundle");
    const {{ DOMLocalization }} = await import("@fluent/dom");

    const bundle = new FluentBundle(locale);

    for (const ftlPath of FTL_FILES) {{
      try {{
        const content = await fetchFTL(ftlPath, locale);
        bundle.addResource(new FluentResource(content));
      }} catch {{
        // FTL file not found — skip
      }}
    }}

    function* generateBundles() {{ yield bundle; }}
    document.l10n = new DOMLocalization([], generateBundles);
    document.l10n.connectRoot(document.documentElement);
    document.l10n.translateRoots();
  }} catch (e) {{
    console.warn("acorn-web: Fluent setup failed. Install @fluent/bundle and @fluent/dom.", e);
  }}
}}
"#
    );

    let output_path = output_dir.join("fluent-setup.mjs");
    std::fs::write(&output_path, module_content).map_err(|e| {
        Error::Custom(format!("Failed to write fluent-setup.mjs: {e}"))
    })?;

    Ok(())
}
