//! Resolves `chrome://` and `resource://` URLs to filesystem paths using Firefox's
//! `chrome-map.json`, generated by `./mach build-backend --backend ChromeMap`.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use thiserror::Error;

#[derive(Debug, Error)]
pub enum ChromeMapError {
    #[error("Failed to read chrome-map.json: {0}")]
    Io(#[from] std::io::Error),
    #[error("Failed to parse chrome-map.json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("Invalid chrome-map.json structure: {0}")]
    InvalidStructure(String),
    #[error("No mapping found for URL: {0}")]
    NoMappingFound(String),
    #[error("Invalid URL: {0}")]
    InvalidUrl(String),
}

pub struct ChromeMapResolver {
    /// Sorted by prefix length descending for longest-match-first lookup.
    prefix_map: Vec<(String, String)>,
    alias_map: HashMap<String, String>,
    /// Maps objdir-relative paths to source-relative paths.
    source_map: HashMap<String, String>,
    firefox_dir: PathBuf,
}

impl ChromeMapResolver {
    pub fn new(firefox_dir: &Path, chrome_map_path: &Path) -> Result<Self, ChromeMapError> {
        let content = std::fs::read_to_string(chrome_map_path)?;
        let parsed: serde_json::Value = serde_json::from_str(&content)?;

        let arr = parsed
            .as_array()
            .ok_or_else(|| ChromeMapError::InvalidStructure("expected top-level array".into()))?;
        if arr.len() < 3 {
            return Err(ChromeMapError::InvalidStructure(
                "expected at least 3 elements".into(),
            ));
        }

        // prefixMap: { prefix: [bundlePath] }
        let mut prefix_map: Vec<(String, String)> = arr[0]
            .as_object()
            .ok_or_else(|| ChromeMapError::InvalidStructure("prefixMap not an object".into()))?
            .iter()
            .filter_map(|(k, v)| {
                let bundle = v.as_array()?.first()?.as_str()?;
                Some((k.clone(), bundle.to_string()))
            })
            .collect();
        prefix_map.sort_by(|a, b| b.0.len().cmp(&a.0.len()));

        // aliasMap: { url: url }
        let alias_map: HashMap<String, String> = arr[1]
            .as_object()
            .ok_or_else(|| ChromeMapError::InvalidStructure("aliasMap not an object".into()))?
            .iter()
            .filter_map(|(k, v)| Some((k.clone(), v.as_str()?.to_string())))
            .collect();

        // sourceMap: { objdir_path: [source_path, ...] }
        let source_map: HashMap<String, String> = arr[2]
            .as_object()
            .ok_or_else(|| ChromeMapError::InvalidStructure("sourceMap not an object".into()))?
            .iter()
            .filter_map(|(k, v)| {
                let source = v.as_array()?.first()?.as_str()?;
                Some((k.clone(), source.to_string()))
            })
            .collect();

        Ok(Self {
            prefix_map,
            alias_map,
            source_map,
            firefox_dir: firefox_dir.to_path_buf(),
        })
    }

    /// Checks if a URL is a `chrome://` or `resource://` internal URL.
    pub fn is_internal_url(&self, url: &str) -> bool {
        url.starts_with("chrome://") || url.starts_with("resource://")
    }

    /// Resolves a `chrome://` or `resource://` URL to an absolute filesystem path.
    pub fn resolve_url(&self, url: &str) -> Result<PathBuf, ChromeMapError> {
        if !self.is_internal_url(url) {
            return Err(ChromeMapError::InvalidUrl(url.to_string()));
        }

        // Step 1: Resolve aliases (recursive, max depth 10)
        let resolved_url = self.resolve_alias(url, 10)?;

        // Step 2: Find longest matching prefix
        self.resolve_via_prefix(&resolved_url)
    }

    fn resolve_alias(&self, url: &str, depth: usize) -> Result<String, ChromeMapError> {
        if depth == 0 {
            return Ok(url.to_string());
        }
        match self.alias_map.get(url) {
            Some(target) => self.resolve_alias(target, depth - 1),
            None => Ok(url.to_string()),
        }
    }

    fn resolve_via_prefix(&self, url: &str) -> Result<PathBuf, ChromeMapError> {
        for (prefix, bundle_path) in &self.prefix_map {
            if let Some(suffix) = url.strip_prefix(prefix.as_str()) {
                // If the bundle_path is itself a chrome:// or resource:// URL,
                // recursively resolve through prefixMap.
                if bundle_path.starts_with("chrome://") || bundle_path.starts_with("resource://") {
                    let chained_url = format!("{bundle_path}{suffix}");
                    return self.resolve_via_prefix(&chained_url);
                }

                let objdir_path = format!("{bundle_path}/{suffix}");
                return self.lookup_source(&objdir_path);
            }
        }

        // Implicit fallback: resource://gre/ maps to dist/bin/ at Firefox runtime
        // but isn't in the prefixMap. Handle it so prefix chains that resolve
        // through resource://gre/ (e.g. resource://content-accessible/) work.
        if let Some(suffix) = url.strip_prefix("resource://gre/") {
            let objdir_path = format!("dist/bin/{suffix}");
            return self.lookup_source(&objdir_path);
        }

        Err(ChromeMapError::NoMappingFound(url.to_string()))
    }

    fn lookup_source(&self, objdir_path: &str) -> Result<PathBuf, ChromeMapError> {
        let source_path = self
            .source_map
            .get(objdir_path)
            .ok_or_else(|| ChromeMapError::NoMappingFound(objdir_path.to_string()))?;
        Ok(self.firefox_dir.join(source_path))
    }
}
